### ISSUE TITLE
Failure in GetMediaWorker for streamName error when running KinesisVideoRekognitionIntegrationExampleTest

### ISSUE THREAD

**Issue by mapavia** [aws/amazon-kinesis-video-streams-parser-library#63]
I get this error after a few seconds of running KinesisVideoRekognitionIntegrationExampleTest. I use Eclipse and run JUnit Test. I think I've configured all that I need to in the code. I'm not sure what I'm doing wrong.

```
2019-06-26 07:46:59 ERROR Worker:Worker.run caught exception, sleeping for 1000 milli seconds!
sjava.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.runProcessLoop(Worker.java:602)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:572)
	at com.amazonaws.kinesisvideo.parser.kinesis.KinesisDataStreamsWorker.run(KinesisDataStreamsWorker.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-06-26 07:46:59 ERROR Worker:Worker.run caught exception, sleeping for 1000 milli seconds!
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.runProcessLoop(Worker.java:602)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:572)
	at com.amazonaws.kinesisvideo.parser.kinesis.KinesisDataStreamsWorker.run(KinesisDataStreamsWorker.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Rendering non-sampled frame with previous rekognized results...
07:46:59.778 [pool-2-thread-2] ERROR com.amazonaws.kinesisvideo.parser.examples.GetMediaWorker - Failure in GetMediaWorker for streamName <stream_name>  com.amazonaws.AbortedException: 
```

**Comment by mapavia** [comment]
I am now getting a lot of `cannot find symbol` to my aws class. -_-

**Comment by bdhandap** [comment]
Are you importing all the dependent AWS classes through Maven?

**Comment by mapavia** [comment]
Yup, works now. Something was wrong with my Maven configuration.

**Comment by Alex-fanfanfan** [comment]
Hi Mapavia,

I am getting the same issue with you. Could you please tell me what is wrong with the Maven configuration?

**Comment by jtheanalytica** [comment]
Hi @bdhandap. 
Hi @mapavia.
Please let me know how you solved this issue. 
Regards
https://github.com/aws/amazon-kinesis-video-streams-parser-library/issues/75

**Comment by jtheanalytica** [comment]
#75
