### ISSUE TITLE
Face rekogniton in rtsp link

### ISSUE THREAD

**Issue by dhrumilsheth9** [aws/amazon-kinesis-video-streams-parser-library#64]
I have a very quick question regarding face recognition in the rtsp link. Do this code provide support for the rtsp link or I have to upload the mkv file only?

**Comment by zhiyua-git** [comment]
Hi @dhrumilsheth9 ,

If you are just trying to send the data from rtsp link, you can refer to https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-gstreamer-plugin.html#examples-gstreamer-plugin-docker. Install docker and pull down the image then run it with your rtsp link and stream name.

**Comment by dhrumilsheth9** [comment]
Thank you for replying. I have already sent the data through the rtsp link and I can see the video in aws kinesis video stream console. But do this code only supports video file? I am asking because when I run the video file this code gives correct output by recognizing the face and shows video on another kinesis video stream but when I run rtsp video stream, the rekognized video stream shows a blank screen. In cloud watch the error is java.lang.RuntimeException: long term. Here is a full stack trace 
`java.lang.RuntimeException: long term
at org.jcodec.codecs.h264.decode.RefListManager.reorder(RefListManager.java:156)
at org.jcodec.codecs.h264.decode.RefListManager.buildRefListP(RefListManager.java:79)
at org.jcodec.codecs.h264.decode.RefListManager.getRefList(RefListManager.java:42)
at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:71)
at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:152)
at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103)
at com.amazonaws.kinesisvideo.parser.utilities.H264FrameDecoder.decodeH264Frame(H264FrameDecoder.java:64)
at com.amazonaws.kinesisvideo.parser.examples.lambda.H264FrameProcessor.process(H264FrameProcessor.java:104)
at com.amazonaws.kinesisvideo.parser.utilities.FrameVisitor$FrameProcessor.process(FrameVisitor.java:73)
at com.amazonaws.kinesisvideo.parser.utilities.FrameVisitor$FrameVisitorInternal.visit(FrameVisitor.java:105)
at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:128)
at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visitAll(CompositeMkvElementVisitor.java:67)
at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visit(CompositeMkvElementVisitor.java:54)
at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:128)
at com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader.apply(StreamingMkvReader.java:132)
at com.amazonaws.kinesisvideo.parser.examples.GetMediaForFragmentListWorker.run(GetMediaForFragmentListWorker.java:64)
at com.amazonaws.kinesisvideo.parser.examples.lambda.KinesisVideoRekognitionLambdaExample.processRekognizedOutputs(KinesisVideoRekognitionLambdaExample.java:124)
at com.amazonaws.kinesisvideo.parser.examples.lambda.KinesisVideoRekognitionLambdaExample.handleRequest(KinesisVideoRekognitionLambdaExample.java:164)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:259)
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
  `
