### ISSUE TITLE
Test Failure probably due to regression

### ISSUE THREAD

**Issue by jlong29** [aws/amazon-kinesis-video-streams-parser-library#90]
During build of 2e93ba3ec843677c3128a6b4355e67f340ef0859 I had 2 tests fail, which generated the following file:

-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 72, Failures: 2, Errors: 0, Skipped: 9, Time elapsed: 26.291 sec <<< FAILURE! - in TestSuite
testFragmentMetadata_NoFragementMetadata_withWebm on testFragmentMetadata_NoFragementMetadata_withWebm(com.amazonaws.kinesisvideo.parser.utilities.FragmentMetadataVisitorTest)(com.amazonaws.kinesisvideo.parser.utilities.FragmentMetadataVisitorTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.nio.file.NoSuchFileException: testdata/big-buck-bunny_trailer.webm
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.amazonaws.kinesisvideo.parser.TestResourceUtil.getTestInputStream(TestResourceUtil.java:37)
	at com.amazonaws.kinesisvideo.parser.utilities.FragmentMetadataVisitorTest.testFragmentMetadata_NoFragementMetadata_withWebm(FragmentMetadataVisitorTest.java:269)

testWithWebmVideo on testWithWebmVideo(com.amazonaws.kinesisvideo.parser.utilities.SimpleFrameVisitorTest)(com.amazonaws.kinesisvideo.parser.utilities.SimpleFrameVisitorTest)  Time elapsed: 0.352 sec  <<< FAILURE!
java.nio.file.NoSuchFileException: testdata/big-buck-bunny_trailer.webm
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.amazonaws.kinesisvideo.parser.TestResourceUtil.getTestInputStream(TestResourceUtil.java:37)
	at com.amazonaws.kinesisvideo.parser.utilities.SimpleFrameVisitorTest.getInputStreamParserByteSource(SimpleFrameVisitorTest.java:124)
	at com.amazonaws.kinesisvideo.parser.utilities.SimpleFrameVisitorTest.getClustersByteSource(SimpleFrameVisitorTest.java:120)
	at com.amazonaws.kinesisvideo.parser.utilities.SimpleFrameVisitorTest.testWithWebmVideo(SimpleFrameVisitorTest.java:71)

I believe there used to be a "testdata" folder containing the test video file. Is this correct?

**Comment by MushMal** [comment]
Not sure if this is a regression. Does this reproduce on the latest? Resolving due to inactivity
